#!/bin/bash
# Generate comprehensive skill audit report

OUTPUT_FILE="${1:-skill-audit-report.md}"
SKILLS_DIR="${OPENCLAW_SKILLS_DIR:-$HOME/.openclaw/workspace/skills}"

echo "Generating report..."

cat > "$OUTPUT_FILE" << 'EOF'
# 🔒 OpenClaw Skill Security Audit Report

**Generated:** $(date -u '+%Y-%m-%d %H:%M UTC')
**System:** $(hostname)
**Skills Directory:** $SKILLS_DIR

---

## 📊 Executive Summary

| Metric | Count |
|--------|-------|
| Total Skills Installed | $(find $SKILLS_DIR -mindepth 1 -maxdepth 1 -type d | wc -l) |
| High Risk | $(grep -c "🔴" <<< "$(./scan.sh 2>&1)" 2>/dev/null || echo 0) |
| Medium Risk | $(grep -c "🟡" <<< "$(./scan.sh 2>&1)" 2>/dev/null || echo 0) |
| Low Risk | $(grep -c "🟢" <<< "$(./scan.sh 2>&1)" 2>/dev/null || echo 0) |

---

## 🚨 High Risk Skills (Needs Attention)

EOF

# Scan for high risk
for skill in "$SKILLS_DIR"/*/; do
    if [ -d "$skill" ]; then
        scripts_dir="$skill/scripts"
        if [ -d "$scripts_dir" ]; then
            if grep -r -E "(exec|eval|system|subprocess)" "$scripts_dir" 2>/dev/null | grep -v "Binary" | head -1; then
                name=$(basename "$skill")
                echo "### 🔴 $name" >> "$OUTPUT_FILE"
                echo "" >> "$OUTPUT_FILE"
                echo "- **Risk:** Command execution detected" >> "$OUTPUT_FILE"
                echo "- **Location:** $skill" >> "$OUTPUT_FILE"
                echo "" >> "$OUTPUT_FILE"
            fi
        fi
    fi
done

cat >> "$OUTPUT_FILE" << 'EOF'

---

## 🟡 Medium Risk Skills (Review Recommended)

EOF

for skill in "$SKILLS_DIR"/*/; do
    if [ -d "$skill" ]; then
        scripts_dir="$skill/scripts"
        risk=""
        reasons=()
        
        if [ -d "$scripts_dir" ]; then
            if grep -r -E "(curl|wget|fetch|http)" "$scripts_dir" 2>/dev/null | grep -v "Binary" | head -1; then
                reasons+=("Network access")
            fi
            if grep -r -E "(>|write|save)" "$scripts_dir" 2>/dev/null | grep -v "Binary" | head -1; then
                reasons+=("File write operations")
            fi
        fi
        
        if [ ${#reasons[@]} -gt 0 ]; then
            name=$(basename "$skill")
            echo "### 🟡 $name" >> "$OUTPUT_FILE"
            for reason in "${reasons[@]}"; do
                echo "- ${reason}" >> "$OUTPUT_FILE"
            done
            echo "" >> "$OUTPUT_FILE"
        fi
    fi
done

cat >> "$OUTPUT_FILE" << 'EOF'

---

## 🟢 Low Risk Skills (Generally Safe)

EOF

for skill in "$SKILLS_DIR"/*/; do
    if [ -d "$skill" ]; then
        scripts_dir="$skill/scripts"
        has_risk=false
        
        if [ -d "$scripts_dir" ]; then
            if grep -r -E "(exec|eval|system|curl|wget|fetch|>|write|save)" "$scripts_dir" 2>/dev/null | grep -v "Binary" | head -1; then
                has_risk=true
            fi
        fi
        
        if [ "$has_risk" = false ]; then
            name=$(basename "$skill")
            echo "### 🟢 $name" >> "$OUTPUT_FILE"
            echo "- Read-only operations only" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        fi
    fi
done

cat >> "$OUTPUT_FILE" << 'EOF'

---

## 💡 Recommendations

### Immediate Actions
- [ ] Review all 🔴 High Risk skills before use
- [ ] Remove skills you don't recognize
- [ ] Secure .env file: `chmod 600 ~/.openclaw/workspace/.env`

### Monthly Tasks
- [ ] Run this audit report
- [ ] Rotate API keys
- [ ] Remove unused skills

---

*Generated by OpenClaw Skill Scanner*
EOF

echo "✅ Report generated: $OUTPUT_FILE"
echo "📄 Open with: cat $OUTPUT_FILE"
